### ISSUE TITLE
Use more descriptive place holders

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/snippets#10]
How about using the following place holders, but still support the old ones for backward compatibility.

{user} instead of %u
{reporter} instead of %r
{handler} instead of %h
{project} instead of %p

**Comment by atrol** [comment]
Introducing a better readable synatx makes sense, especially if you are thinking about adding further fields to snippets.

But I don't like that much to have more than one way to get exactly the same.
There will always be questions like:
Which is the better one, when to choose the one, when to choose the other, ...

Also in terms of runtime performance and code complexity, it's better to have just one method.

I would prefer a solution where we have just one new syntax and the old syntax is converted to the new one in an upgrade step.

Just an additional idea, implement something (e.g. keyword followed by:) which allows a bit more flexibility for extensions in future versions:
{field:user}
{field:project}
{code:some PHP code} // maybe a bit too much and questionable concering security
{function:current_date}
...

**Comment by vboctor** [comment]
I'll create a pull request.  The format I'll be using is: {user}, {reporter}, {handler}, {project}, {today}, {today+2}, etc.
