### ISSUE TITLE
Use REST API instead of xmlhttprequest

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/snippets#16]
The xmlhttprequest is being deprecated in MantisBT v2.3.0.  Hence, snippets should publish its own REST APIs via the new framework and leverage that to power its functionality.

**Comment by dregad** [comment]
@vboctor I would appreciate if you could kindly review the commit I just pushed to https://github.com/dregad/snippets/tree/rest and let me know your feedback. Thanks in advance !

**Comment by vboctor** [comment]
@dregad done.  Looks good.  I have added few comments  / questions to the commit.
