### ISSUE TITLE
Plugin folder structure

### ISSUE THREAD

**Issue by merlin-tc** [mantisbt-plugins/snippets#22]
Would it be possible to move all files of this repo to a subfolder called "Snippets"?

We are using an automated process to deploy mantis and the most useful plugins.
The snippets repo is the only plugin that is different from all other plugins we pull from github, so having a unified structure would be fantastic.

Thank you!

**Comment by dregad** [comment]
> Would it be possible to move all files of this repo to a subfolder called "Snippets"?

It used to be like that. We actually changed the structure about a year ago, the rationale being that a lot of people actually install the plugins as git repositories straight into the plugins/ directory, and it does not bring much value to maintain the extra subdirectory (except in some specific cases, like the Source Integration plugin)

So I'm afraid you're request is a "won't fix"... Sorry.

**Comment by merlin-tc** [comment]
Oh, I wasn't aware that it used be be like that, no need to say sorry.
Should have checked some earlier revisions.
I will integrate a way to handle both ways in our deployment script. Thanks for your time and the plugin!
