### ISSUE TITLE
In vrs 2.6.0 MantisBT does not work in chrome, firefox, internet explorer only

### ISSUE THREAD

**Issue by venturitsoft** [mantisbt-plugins/snippets#23]
does not work in chrome, firefox, internet explorer only, does not display list of values with snippets

I need to do some additional configuration in the web browser

Thanks,

**Comment by venturitsoft** [comment]
![snippet_1](https://user-images.githubusercontent.com/26033602/31036392-aba7be60-a531-11e7-9767-1ee1862e1885.jpg)
![snippet_2](https://user-images.githubusercontent.com/26033602/31036391-aba2d58a-a531-11e7-8e5f-3a9a48366ea0.jpg)
![snippet_3](https://user-images.githubusercontent.com/26033602/31036390-ab9ccc44-a531-11e7-9043-33603260034b.jpg)
![snippet_4](https://user-images.githubusercontent.com/26033602/31036393-aba9e924-a531-11e7-95c8-136e25c88f80.jpg)

**Comment by atrol** [comment]
See my comment at http://www.mantisbt.org/bugs/view.php?id=23419#c57859

**Comment by dregad** [comment]
@venturitsoft I use the plugin everyday in Firefox without issues, and just tested with Chrome it works as expected, no errors or messages in the browser's console.

Must be something with your local settings.

**Comment by venturitsoft** [comment]
Thanks dregad, 

Do you have any other recommendations to analyze in my local assembly?
thanks

**Comment by dregad** [comment]
Since I can't reproduce the problem, I'm afraid not, sorry.

**Comment by cs97jjm3** [comment]
I have this problem did anyone solve it ?

**Comment by dregad** [comment]
Not that I know
