### ISSUE TITLE
Improvement to UI

### ISSUE THREAD

**Issue by sandyjmh** [mantisbt-plugins/Snippets#33]
Hi, I wanted to make a couple of suggestions for the snippet plugin that I think would improve UI experience. 
1. I find it difficult to find the snippet I want when we have many snippets. A simple fix would be to have snippets ordered alphabetically but ideally we'd love to see a way to define order and group snippets.
2. Would be great to have the section for creating snippets at the top of the page rather than the bottom.  If you have a lot of snippets, it's alot of scrolling if you want to add a new one. Same goes for the action drop down box and 'Go' button. Perhaps provide this option at the top of the snippet list as well as the bottom. 

thanks,
Sandra

**Comment by sandyjmh** [comment]
for snippet action (i.e. edit or delete) maybe have these as buttons next to snippet itself rather than dropdown + go...

**Comment by dregad** [comment]
@sandyjmh thanks for your suggestions. Could you please open separate issues for each enhancement ?

Cheers

PS: pull requests are welcome...

**Comment by sandyjmh** [comment]
thanks @dregad - have created 3 new separate issues.
