### ISSUE TITLE
Re-locate Create snippet section

### ISSUE THREAD

**Issue by sandyjmh** [mantisbt-plugins/Snippets#35]
To prevent having to scroll through a long list of existing snippets, the create snippet section should be moved to the top of the page.

**Comment by dregad** [comment]
I kind of like it at the bottom myself - from my experience it is more common to update an existing Snippet, rather than creating new ones. 

Alternatives: a link to scroll to the Snippets creation section, or move it to a separate page.

**Comment by sandyjmh** [comment]
Link to creation section would do the trick...

**Comment by dregad** [comment]
I'm looking forward to receiving your pull request.
