### ISSUE TITLE
Provide easy access to Edit/Delete option for snippets.

### ISSUE THREAD

**Issue by sandyjmh** [mantisbt-plugins/Snippets#36]
Edit and delete options for existing snippets should be button options displayed next to each snippet rather than requiring a selection checkbox and scrolling to the bottom of the screen for dropdown box selection and clicking Go. Or you can replicate the dropdown box and Go at the top of the table but preference is for buttons next to the snippet itself.

**Comment by dregad** [comment]
The reason it was done this way, was to let the user edit multiple snippets at the same time. It would no longer be possible to do this with your proposed enhancement. Probably not a huge deal though.

Pull request welcome.

**Comment by sandyjmh** [comment]
I understand the need to delete multiple snippets at a time but can't see a need to edit multiple snippets at the same time. thx.
