### ISSUE TITLE
Real names instead of user names used for placeholders

### ISSUE THREAD

**Issue by atrol** [mantisbt-plugins/Snippets#37]
Placeholders for users are replaced by the real name instead of the user name if the following configuration is used and the access level of the current user is >=  $g_show_user_realname_threshold
```
$g_show_realname = ON;
$g_show_user_realname_threshold = DEVELOPER;
```
When using such a snippet, real names are published to any user, even those who are not allowed to view real names.

**Comment by dregad** [comment]
I'm tagging this with *security* because it's a potential information disclosure.
