### ISSUE TITLE
snippets dropboxes do not appear

### ISSUE THREAD

**Issue by ibyssorucevap** [mantisbt-plugins/Snippets#45]
After version 2.23.0 update, the snippets disappeared through the text box.
No problem in the plugin settings section. but the selection snippets dropboxes do not appear where the text is written.
Can you help?

**Comment by dregad** [comment]
We use Snippets plugin (v2.2.5) on mantisbt.org 2.23 without any issues, also not able to reproduce locally.

I suggest you check in your browser's console for any errors, maybe the javascript is not loading.

**Comment by ibyssorucevap** [comment]
![image](https://user-images.githubusercontent.com/44139748/71314598-326fcb80-245c-11ea-9728-19386a092f35.png)

how can I solve this?

**Comment by dregad** [comment]
Check your webserver logs, to find out why the AJAX request failed with HTTP 500 error.

This is not a bug with the plugin, but a problem with your server.
