### ISSUE TITLE
Does not work with Simple Markdown Editor in Report Issue textareas

### ISSUE THREAD

**Issue by priocomdevops** [mantisbt-plugins/Snippets#47]
The snippets get disabled when the plugin https://github.com/ejyothi/MantisBT-MarkDownEditor is installed.

**Comment by dregad** [comment]
The plugin uses jQuery to inject the Snippets selection list before the configured TextArea fields; I don't know how the MarkDownEditor plugin works internally, but I suppose it's changing the markup in such a way that Snippets is no longer able to identify the input fields.

Unfortunately, I don't see how this could be addressed and we have to consider Snippets as incompatible with the MarkDownEditor plugin, unless their developers have an idea.
