### ISSUE TITLE
Snippets stopped working since update to Mantis 2.25.0

### ISSUE THREAD

**Issue by fpaquet** [mantisbt-plugins/Snippets#56]
All Snippets dropdowns are gone.

Opening plugin configuration page reveals:

APPLICATION ERROR #2505

Das Plugin „Snippets“ muss aktualisiert werden, bevor Sie auf diese Seite zugreifen können.

Bitte benutzen Sie die „Zurück“-Taste Ihres Browsers, um auf die vorhergehende Seite zurückzukehren. Dort können Sie den hier angezeigten Eintrag korrigieren oder eine andere Aktion ausführen. Über das Menü können Sie auch direkt zu einer anderen Aktion wechseln.

**Comment by fpaquet** [comment]
We're using an up-to-date clone of https://github.com/mantisbt-plugins/Snippets

**Comment by dregad** [comment]
> We're using an up-to-date clone of https://github.com/mantisbt-plugins/Snippets

The plugin has formal releases, so it would be more useful if you mentioned the actual version you're on.

Based on your usage of the word _clone_, I would assume that you've recently pulled the plugin's code when you updated Mantis, but did not actually upgrade the plugin nor ran the _Admin Checks_ after upgrading Mantis [as explained in the Admin Guide](https://mantisbt.org/docs/master/en-US/Admin_Guide/html-desktop/#admin.install.postcommon).

Snippets 2.3.0 introduced a schema change so you need to upgrade the plugin via Manage Plugins Page.

**Comment by fpaquet** [comment]
Of course we have executed the _Admin Checks_ as explained in the Admin Guide.
Everything was green.

When we try to click on the "Upgrade" button in the plugin management, we get:

APPLICATION ERROR #2503

Aktualisierung des Plugin-Schemas ist in Block #1 fehlgeschlagen.

Bitte benutzen Sie die „Zurück“-Taste Ihres Browsers, um auf die vorhergehende Seite zurückzukehren. Dort können Sie den hier angezeigten Eintrag korrigieren oder eine andere Aktion ausführen. Über das Menü können Sie auch direkt zu einer anderen Aktion wechseln.

**Comment by fpaquet** [comment]
APPLICATION ERROR #2503

Aktualisierung des Plugin-Schemas ist in Block #1 fehlgeschlagen.
means
Plugin schema update failed in block #1.

**Comment by dregad** [comment]
You are obviously not using the [latest release](https://github.com/mantisbt-plugins/Snippets/releases/tag/v2.3.2) as this error was actually fixed last night (see #55).

**Comment by fpaquet** [comment]
Thank you, we'll try it. :-)

**Comment by fpaquet** [comment]
Snippets are working again after pulling the changes and hitting "Update" in plugin manager.
Thank you
