### ISSUE TITLE
Snippets configuration does not honor project level access.

### ISSUE THREAD

**Issue by sandyjmh** [mantisbt-plugins/Snippets#57]
Snippets configuration does not honor project level access. Configuration settings will only take into consideration a users global access and not allow access to snippets depending on their project level access. i.e. If snippets is set to be usable by developers and above and a user has 'viewer' access globally and 'developer' access for a specific project, they will
not be able to access snippets at all.

Ideally, the user should be able to access snippets in specific projects where they have the relevant permitted access level.

**Comment by dregad** [comment]
Considering that the Snippets themselves are global objects (i.e. not project-specific), what you are asking is not feasible without an important redesign of the plugin.

**Comment by dregad** [comment]
Note: if you are willing to submit a pull request to implement this feature, I'll gladly reopen this and review your contribution.
