### ISSUE TITLE
Sort order of Snippets on name instead of id

### ISSUE THREAD

**Issue by TomR** [mantisbt-plugins/Snippets#58]
Is it possible to change te sort order of the Snippets when using them. The are now sorted by 'id' which is not a usefull field.
I would rather have them sorted by name.

**Comment by dregad** [comment]
As far as I can tell, Snippets *are* sorted alphabetically, not by id...

This is the snippets available on my dev box for my user id (global + personal)
| id  | name           |
|-----|----------------|
| 208 | aaa            |
| 209 | perso snippet  |
| 211 | Test issue #46 |
| 221 | 123            |

And this is how they're displayed in the UI
![image](https://user-images.githubusercontent.com/449891/152647776-bf014352-4477-438e-b6f9-f40f3d5f5997.png)

As you can see, snippet id 221 is listed first.
