### ISSUE TITLE
Application Error #2800 when trying to delete not selected snippet

### ISSUE THREAD

**Issue by gceballosl** [mantisbt-plugins/Snippets#65]
When trying to delete a not selected snippet it appears a message saying "Please select at least one snippet to process", after click the "OK" button, it appears an error message saying:

"Application Error #2800 Invalid form security token. This could be caused by a session timeout, or accidentally submitting the form twice.
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section."

If you click the "Go back one page" button on the browser it redirects to a page where it says the document has expired, here the complete message:

"Document Expired

This document is no longer available.

The requested document is not available in Firefox’s cache.

As a security precaution, Firefox does not automatically re-request sensitive documents.
Click Try Again to re-request the document from the website.&quot;

If you click reload page or refresh it, you will see again the Application Error #2800, if you click "Go back one page" button on the browser it will redirect to the snippet list page (https://www.mantisbt.org/bugs/plugin.php?page=Snippets/snippet_list), then now if you click again "Go back one page" button now it will successfully reload the snippet list page.

![deleteNotSelectedSnippetMessage](https://github.com/mantisbt-plugins/Snippets/assets/142336848/5362a862-99be-4715-a6cb-02b10140fd73)
![deleteNotSelectedSnippetApplicationError2800_DocumentExpiredPageReload](https://github.com/mantisbt-plugins/Snippets/assets/142336848/e679ed16-56cf-4871-afae-586bd5a97089)
![deleteNotSelectedSnippetApplicationError2800_BackButtonActionDocumentExpired](https://github.com/mantisbt-plugins/Snippets/assets/142336848/ccc82bbe-536a-4355-83cb-503647fa03bf)
![deleteNotSelectedSnippetApplicationError2800_BackButtonAction](https://github.com/mantisbt-plugins/Snippets/assets/142336848/e29093db-7bdf-49f7-a6e7-d62472b1455c)
![deleteNotSelectedSnippet](https://github.com/mantisbt-plugins/Snippets/assets/142336848/d49a940b-9441-4331-bdd6-e5538948f270)

**Comment by gceballosl** [comment]
Submitting this issue accordingly to this note from Mantis bug tracking system

https://mantisbt.org/bugs/view.php?id=32836

**Comment by dregad** [comment]
The 2800 error often occurs because the PHP garbage collection killed the session. This is a known problem with MantisBT, and unfortunately can't be controlled by the software - it requires changing php.ini settings.

For more information, please read [the manual](https://www.mantisbt.org/docs/master/en-US/Admin_Guide/html-desktop/#admin.troubleshooting.errors.2800).

Unfortunately, I have not been able to reproduce this, even when forcing session expiration so I don't know what to tell you... I this consistently repeatable on your end ?

**Comment by dregad** [comment]
Closed due to lack of feedback. Feel free to reopen.
