### ISSUE TITLE
Hang Chrome while loading snippets

### ISSUE THREAD

**Issue by cyril-bouthors** [mantisbt-plugins/snippets#7]
We've found out that the Snippets plugin hangs Chrome for all the time it loads the snippets with Ajax.

This is OK if you have only a few snippets and working with a fast connexions but we have tons of snippets and some of my colleagues are sometimes working over a slow connection and Mantis bugs pages can take up to 15 seconds to load.

We have other plugins with Ajax loading and they do not hang the browser while loading, even if it takes several seconds to load.

I haven't tested other browsers.

To reproduce the issue:

  - add tons of snippets in Mantis, probably with a script or SQL query
 - test from a slow connection or simulate a slow connection with a sleep in the foreach loop of pages/snippet_list.php

**Comment by dregad** [comment]
Hello Cyril,

Can you please be more accurate in describing what the issue is ? what is a "ton" of snippets ? what is a "slow" connection ? What page(s) are slow to load ?

I tested this locally with 1'000 randomly generated snippets and the page (view.php) loaded just fine in < 0.3s

**Comment by cyril-bouthors** [comment]
Very sorry about that but after a long investigation, this weird issue was coming from a memory leak in a totally unrelated Chrome Extension that only caused problem in Snippets.

**Comment by dregad** [comment]
Thanks for the feedback.
